[gcp_service_account]
type = "service_account"
project_id = "workflow-479010"
private_key_id = "cadf400437b0bb835f3d7ff01b5faf6ccf785d89"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCb9bjoy6XKHX9h
8QYZ4CE0DKbujgyB/xt0PvM6Ok3si8TsHrGdTyeRb1km8LGDkSbFHP4jvDN/EwAQ
WuR4UkOnGwJvuWHaN4vnBuJXCAVbAA1Xu7orBLH/UZWoxXN/T+BpxHs33HC+r6/1
7WwlxfmKyMz/RTrRHgcXfg8L6rLTxuWvS1uGZXFbZpa4wt79Qvl2bp+R4F+YYCIV
9m7iSFT+lM0lW2KO4YTH2pDR7aC07qYgam1CojO1VRCI4I43nSWJouVddVG75zeh
fzpJ3hpsc4K7SD25bWdJwzzG8c1ECB0SKClS4iyTFPnH1gSIO4MGBx/2NzLAfKnA
xPPWkXuxAgMBAAECggEANBh/BUgtX5e92rX7nz4WaUAGrO4HMI9KGOkEL0GVkPvZ
MjRIiS8NHRAQPCkvaq7cQACgxcgSfZKXtV7fLW/xSEsF49MNZCqk0W2jwoWb4Fti
mZlMJR2C5bHXZ5JZM8A3Sq1GqZC5moCuKtx9gRqh8iGEFIsIDB1XKhpCJW1nAcVL
n+I3FiF1I1PvvDxHWSv2logye3H+vocWphNKFxg36wcbDP5oyjM3n7ZDDuUN5A3A
F8GO8UMekNRXQsEeAX2vGhfGu5lNGuG5Any8strm9h/VWpea7416zafMKngqlkpC
zKj0Lf+lqQUEHZOZD74nr5fcPYr2C6X4qwse3PiA/wKBgQDNBZpW+2KsZYT/pkzQ
n6MnJjypKz0qwwmxpGrsN0rAc/P8FFtSYKnn6JxiQqw64Vmm+NNVek4gRuxKKaRC
f+rucYuJuzcQUzJVorczUeHKKh8ij4BRfnFhqJwAR6ZC4UBdwieNTCgTej6/FtNo
PENvK0m+rs8K4ZI6AdSDFiWnRwKBgQDCvSP58DXi/8YDzR8HMqai2OOnOYurf5HX
xqYnQcsRVOBTeKabOimg9z2KmH4QJhxscnEkt95LqyMzPgydu4AWb234zBcDhyLv
x7GXDMJFtfTvXwfRk+4nkGOA7XjvqB8wPKVSZTSA5a3gnfbGSTro6TpnI4b2cFS2
zHRDNsixRwKBgQCcCp+lhD9dpwbK7O+Z+WZb7aZNuzMa0McYBWO71Xl3cMlKGtRG
pnuqnkgoIUakqc9qXge7DxNXTaOZ7oeudV2Bjbn+YhdOvYOZ2fZFgRSwoc6Ap2eq
nun8wi+5ps7MKFStB5DC4iu+Z1RKbD0LIJLSkcfW8YVzaqu4qpvsCXcvEQKBgQCE
qN5qNHYxFjZpfoGFoL6drwyebXg1MylCCeREV/Ci9OQAWO9+TUfwjJzS3oD6NUwl
oGxtLAh2GbZYAQwNI57lKbGLzFRdJeDp4WqcUKfDX2nk6yLjZVfWgekW+i7pa+kb
LiUdFS6IJG6n1lQ2zcogwkjz2+Lj3LAI+wy0gQyEnwKBgHSqwlk/ZYJZih19pO7N
VdOtt0l+wy7hRxC0kGz32UlPcAUg5CjPNuvnhmCIfQbtfVXFFdb10ta88spPgjz0
uR3sjd1t0kSzTkcP1sf07Y6sFI5dOEsCcFJ9tszeQJm+aw5oeZEgJNAlrHO0Wg5s
oyJ0zmkxLL0X+i0+9risiX7A
-----END PRIVATE KEY-----"""
client_email = "streamlit-ssc-service@workflow-479010.iam.gserviceaccount.com"
client_id = "107717375273557587741"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-ssc-service%40workflow-479010.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
